homepage/urls.py
from django.urls import path
from .views import inicio, about_me, soon  

urlpatterns = [
    path('', inicio, name='inicio'),
    path('about_me/', about_me, name='about_me'),
    path('soon!/', soon, name='soon!')  
]

messaging/urls.py
from django.urls import path  
from .views import send_message, show_messages

app_name = "messaging"

urlpatterns = [ 
    path("send/", send_message, name="send_message"),
    path("inbox/", show_messages, name="show_messages"),
]

ssr_news_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include("homepage.urls")),
    path('users/', include("users.urls")),
    path('articles/', include("articles.urls")),
    path('notifications/', include("notifications.urls")),
    path('messaging/', include("messaging.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import get_user_profile, user_login, user_register, user_logout, edit_user_profile, change_password

urlpatterns = [
    path('profile/', get_user_profile, name='user_profile'),
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('profile/edit/', edit_user_profile, name='edit_profile'),
    path('change-password/', change_password, name='change_password')
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
from articles.models import Article

def inicio(request):
    articles = Article.objects.all()[:3]
    while len(articles) < 3:
        articles.append(None)  
    return render(request, 'homepage/index.html', {'articles': articles})

def get_github_avatar(username):
    url = f"https://api.github.com/users/{username}"
    try:
        response = requests.get(url)
        response.raise_for_status()  
        data = response.json()
        return data.get("avatar_url", "")
    except requests.RequestException:
        return None

def about_me(request):
    username = "fabrixindex"  
    avatar_url = get_github_avatar(username)
    return render(request, 'homepage/about_me.html', {"avatar_url": avatar_url})

def soon(request):
    return render(request, 'homepage/soon.html')

homepage/templates/homepage/about_me.html
{% extends 'homepage/base.html' %}

{% block title %}TruethLine | About Me{% endblock title %}

{% block content %}
<div class="about-me-wrapper">
    <div class="about-me-box">
        <h2 class="about-me-title">About Me</h2>
        <div class="about-me-wrapper">
            <a href="https://www.linkedin.com/in/fabricio-papetti-5b791a21a/" target="_blank">
                <img src="{{ avatar_url }}" alt="GitHub Profile Picture" class="profile-picture">
            </a>            
        </div>
        
        <section class="about-me-introduction">
            <p>
                Hi! I am <strong>Fabricio Papetti</strong>, a passionate <strong>MERN stack developer</strong> who loves technology and continuous learning. 
                I am self-taught, creative, and constantly motivated to acquire new skills and expand my knowledge every day.
            </p>
            <p>
                Recently, I have been exploring the world of Python, learning how to create efficient solutions with its versatile ecosystem. 
                This new journey has expanded my understanding of programming and reinforced my passion for software development.
            </p>
            <p>
                ¡Hola! Soy <strong>Fabricio Papetti</strong>, un desarrollador MERN de 25 años. Me destaco por mi responsabilidad, organización y 
                enfoque resolutivo, comprometiéndome al 100% en cada proyecto en el que participo. Además, estoy descubriendo Python y 
                experimentando con nuevas herramientas y tecnologías que me inspiran a seguir aprendiendo.
            </p>
        </section>

        <section class="about-me-skills">
            <h3>Technical Skills</h3>
            <ul>
                <li>Node.js, Express, MongoDB, SQL, Git, React</li>
                <li>Python: Django, and basic data analysis</li>
                <li>Web and mobile application development</li>
                <li>API integration and RESTful services</li>
                <li>Version control with Git and GitHub</li>
                <li>Pack Office: Word, Excel, PowerPoint</li>
            </ul>
        </section>

        <section class="about-me-experience">
            <h3>Experience</h3>
            <p>
                I have worked on various projects, leveraging my skills to develop scalable and efficient solutions that improve 
                product quality and user experience. I am always looking to enhance my expertise and deliver exceptional results.
            </p>
            <p>
                As I dive deeper into Python, I am excited to integrate its capabilities into my future projects and bring even more 
                versatility to my development toolkit.
            </p>
        </section>

        <section class="about-me-interests">
            <h3>Personal Interests</h3>
            <p>
                Beyond my professional life, I enjoy reading, learning English, watching movies, playing video games, engaging in sports, 
                and going for walks. These activities help me maintain balance and stay inspired in my work.
            </p>
            <p>
                My recent exploration of Python has also become a hobby, and I look forward to creating projects that merge my curiosity 
                with real-world applications.
            </p>
        </section>

        <section class="about-me-contact">
            <h3>Contact</h3>
            <p>📫 <strong>Email:</strong> <a href="mailto:fabriciopapetti1121@gmail.com">fabriciopapetti1121@gmail.com</a></p>
            <p>🌐 <strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/fabricio-papetti-5b791a21a/" target="_blank">Fabricio Papetti</a></p>
            <p>💻 <strong>GitHub:</strong> <a href="https://github.com/fabrixindex" target="_blank">fabrixindex</a></p>
        </section>
    </div>
</div>
{% endblock content %}

homepage/templates/homepage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TruethLine{% endblock title %}</title>
    <link  href="{% static  'homepage/css/styles.css' %}" rel="stylesheet">
    <link  href="{% static  'articles/css/styles.css' %}" rel="stylesheet">
    <link  href="{% static  'users/css/styles.css' %}" rel="stylesheet">
    <link  href="{% static  'messaging/css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="icon" href="{% static 'homepage/assets/LogoTL.png' %}" type="image/png">
    <link rel="shortcut icon" href="{% static 'homepage/assets/LogoTL.png' %}" type="image/png">
</head>
<body>
    <header>
        <div class="logo">
            <h1>TruethLine</h1>
        </div>
        <nav>
            <div class="menu-container">
            
                <button class="menu-btn" onclick="toggleCategories()">☰</button>
    
                <ul class="navbar">
                    <li id="current-time"></li>
                    <a href="{% url 'inicio' %}"><li>Home</li></a>
                    <a href="{% url 'articles' %}"><li>Top Articles</li></a>
                    <a href="{% url 'messaging:send_message' %}"><li>Send Message</li></a>
                    <a href="{% url 'messaging:show_messages' %}"><li>Show Messages</li></a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'user_profile' %}">
                        <li>
                            {% if user.profile.photo %}
                                <img src="{{ user.profile.photo.url }}" alt="Profile" class="profile-picture-small">
                            {% else %}
                                <img src="{% static 'users/assets/blank-profile-picture.webp' %}" alt="Profile" class="profile-picture-small">
                            {% endif %}
                        </li>
                    </a>
                        <a href="{% url 'logout' %}"><li>Logout</li></a>
                    
                    {% else %}
                        <a href="{% url 'login' %}"><li>Login</li></a>
                        <a href="{% url 'register' %}"><li>Sing Up</li></a>
                    {% endif %}
                </ul>
    
                <ul class="categories" id="categories-menu">
                    <li><a href="{% url 'soon!' %}">Politic</a></li>
                    <li><a href="{% url 'soon!' %}">Economy</a></li>
                    <li><a href="{% url 'soon!' %}">Sport</a></li>
                    <li><a href="{% url 'soon!' %}">World</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        <div class="footer-content">
            <p>&copy; 2024 TruthLine. All rights reserved.</p>
            <p>
                Developed by <a href="https://github.com/fabrixindex" target="_blank">Fabricio Papetti</a>
            </p>
            <p>
                <a href="{% url 'about_me' %}" class="footer-about-link">About Me</a>
            </p>
        </div>
    </footer>
    
    <script src="{% static 'homepage/js/menu.js' %}"></script>
    <script>
        new WOW().init();
    </script>    
</body>
</html>

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %}
TruethLine | Inicio
{% endblock title %}

{% block content %}
<div class="banner">
    <div class="banner-content">
        <h1>Welcome to TruethLine</h1>
        <p>A direct line to the trueth.<br>The latest news, instantly!</p>
        <a href="{% url 'articles' %}" class="btn-primary">View Articles</a>
    </div>
</div>


<section class="latest-news-hp">
    <h2 class="latest-news-hp-title">Latest Headlines</h2>
    <ul id="news-list-hp">
        {% for article in articles %}
        <li class="article-card-hp">
            <h3 class="article-title-hp">{{ article.title }}</h3>
            <p class="article-meta-hp">
                <strong>Author:</strong> {{ article.author }}<br>
                <strong>Published on:</strong> {{ article.publication_date|date:"F j, Y" }}
            </p>
            <p class="article-content-hp">
                {{ article.content|truncatewords:20 }}...
            </p>
            <a href="{% url 'article_detail' article.id %}" class="btn-read-hp" aria-label="Read more about {{ article.title }}">
                Read more
            </a>
        </li>
        {% endfor %}
    </ul>
</section>

<section id="advantages" class="wow animate__animated animate__zoomIn">
    <h2>Why Choose TruethLine?</h2>
    <div id="advantages-list" class="advantages-list-hp">
        <div id="advantage-1" class="wow animate__animated animate__zoomIn">
            <h3>Instant Updates</h3>
            <p>Stay ahead with real-time news updates as they happen.</p>
        </div>
        <div id="advantage-2" class="wow animate__animated animate__zoomIn">
            <h3>Trusted Sources</h3>
            <p>We provide news from the most reliable and verified sources.</p>
        </div>
        <div id="advantage-3" class="wow animate__animated animate__zoomIn">
            <h3>Tailored Content</h3>
            <p>Receive news tailored to your preferences and interests.</p>
        </div>
    </div>
</section>

<style>
    .banner {
        background-image: url("{% static 'homepage/assets/banner.jpg' %}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        color: white;
        text-align: center;
        padding: 80px 20px;
        height: 450px;
        border-radius: 20px;
        margin: 30px auto;
        max-width: 95%;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); 
        margin-bottom: 50px;
        position: relative;
    }

    .banner::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.6); 
        border-radius: 20px; 
        z-index: -1; 
    }
    
    .banner-content {
        max-width: 800px;
        margin: 0 auto;
        position: relative;
    }
    
    .banner h1 {
        font-size: 3.5em; 
        margin-bottom: 20px;
        text-shadow: 4px 4px 10px rgba(0, 0, 0, 1); 
    }
    
    .banner p {
        font-size: 1.7em; 
        margin-bottom: 30px;
        text-shadow: 3px 3px 6px rgba(0, 0, 0, 1); 
    }
</style>

{% endblock content %}

homepage/templates/homepage/soon.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %}
TruethLine | Soon!
{% endblock title %}

{% block content %}

<section class="soon-updates">
    <h2>More Improvements Coming Soon!</h2>
    <p>At TruethLine, we are constantly working to enhance your experience. Soon, you'll be able to enjoy new features, more content, and smoother navigation. Stay tuned!</p>
    <p>Thank you for your continued support. Stay connected to learn about the updates and improvements we have in store for you.</p>
</section>

<style>
    .soon-updates {
        background-color: #f1f3f5; 
        padding: 60px 20px;
        text-align: center;
        border-radius: 15px;
        box-shadow: 0 6px 15px rgba(0, 0, 0, 0.1);
        max-width: 90%;
        margin: 50px auto;
    }

    .soon-updates h2 {
        font-size: 2.8em;
        color: #3e5a76;
        margin-bottom: 20px;
        font-family: 'Georgia', serif;
        text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); 
    }

    .soon-updates p {
        font-size: 1.3em;
        color: #555;
        line-height: 1.8;
        font-family: 'Arial', sans-serif;
        max-width: 800px;
        margin: 0 auto;
    }
</style>


{% endblock content %}