articles/urls.py
from django.urls import path
from .views import getArticles, createArticle, searchArticle, getArticleDetail, deleteArticle, updateArticle

urlpatterns = [
    path('', getArticles, name='articles'),
    path('create/', createArticle, name='create_article'),
    path('<int:id>/', getArticleDetail, name='article_detail'),
    path('search/', searchArticle, name='search_article'),
    path('delete/<int:id>/', deleteArticle, name='delete_article'),
    path('update/<int:id>/', updateArticle, name='update_article'),
]

ssr_news_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include("homepage.urls")),
    path('users/', include("users.urls")),
    path('articles/', include("articles.urls")),
    path('notifications/', include("notifications.urls")),
    path('messaging/', include("messaging.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import get_user_profile, user_login, user_register, user_logout, edit_user_profile, change_password

urlpatterns = [
    path('profile/', get_user_profile, name='user_profile'),
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('profile/edit/', edit_user_profile, name='edit_profile'),
    path('change-password/', change_password, name='change_password')
]

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=255)  
    author = models.CharField(max_length=100)  
    content = models.TextField()  
    publication_date = models.DateTimeField(auto_now_add=True)  
    last_updated = models.DateTimeField(auto_now=True) 
    is_published = models.BooleanField(default=False)  

    def __str__(self):
        return self.title  

articles/forms/articles/forms.py
from django import forms
from ...models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'author', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter the title', 'class': 'form-input'}),
            'author': forms.TextInput(attrs={'placeholder': "Author's name", 'class': 'form-input'}),
            'content': forms.Textarea(attrs={'placeholder': 'Write the article content', 'class': 'form-textarea'}),
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.timezone import now
from .models import Article
from .forms.articles.forms import ArticleForm
from django.contrib.auth.decorators import login_required

def getArticles(request):
    articles = Article.objects.all()  
    return render(request, "articles/articles_list.html", {"articles": articles})

def getArticleDetail(request, id):
    article = get_object_or_404(Article, id=id)
    return render(request, "articles/article_detail.html", {"article": article})

@login_required(login_url="login")
def createArticle(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.publication_date = form.cleaned_data.get('publication_date', now())
            article.last_updated = now()
            article.save()
            return redirect("articles")
    else:
        form = ArticleForm()

    return render(request, "articles/create_article.html", {"form": form})


def searchArticle(request):
    query = request.GET.get('q', '').strip()  
    
    if query:
        articles = Article.objects.filter(title__icontains=query)  
    else:
        articles = Article.objects.all()  
    return render(request, "articles/articles_list.html", {"articles": articles, "query": query})

@login_required(login_url="login")
def deleteArticle(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect("articles")

@login_required(login_url="login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id=id)
    
    if request.method == "POST":
        article_form = ArticleForm(request.POST, instance=article)
        
        if article_form.is_valid():
            article_form.save()
            return redirect('article_detail', id=article.id)  

    else:
        article_form = ArticleForm(instance=article)

    return render(request, "articles/update_article.html", {"form": article_form, "article": article})

articles/templates/articles/article_detail.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %} TruethLine | {{ article.title }} {% endblock title %}

{% block content %}
    <div class="article-container-detail">
        <div class="article-header-detail">
            <h1>{{ article.title }}</h1>
            <p><strong>Author:</strong> {{ article.author }}</p>
            <p><strong>Publication Date:</strong> {{ article.publication_date }}</p>
        </div>
        <div class="article-content-detail">
            <p>{{ article.content }}</p>
        </div>
        <div class="article-actions">
            {% if request.user.is_superuser %}
                <a href="{% url 'update_article' article.id %}" class="btn-update">Update article</a>
                <a href="{% url 'delete_article' article.id %}" class="btn-delete">Delete article</a>
            {% endif %}
            <a href="{% url 'articles' %}" class="btn-back-detail">Back to the list</a>
        </div>        
    </div>
{% endblock content %}

articles/templates/articles/articles_list.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %}TruethLine | Articles{% endblock title %}

{% block content %}
    <h2 class="title-article">Explore Our Latest Articles</h2>
    
    <section class="article-search">
        <h3>Search Article</h3>
        <form action="{% url 'search_article' %}" method="GET" class="search-form">
            <input 
                type="text" 
                name="q" 
                placeholder="Search articles..." 
                value="{{ query }}" 
                aria-label="Search articles" 
                required 
                class="search-input">
            <button type="submit" class="btn-search">Search</button>
        </form>
        {% if query %}
            <p class="search-results">Search results for: <strong>"{{ query }}"</strong></p>
        {% endif %}
    </section>

    <div class="btn-container">
        <a href="{% url 'create_article' %}" class="btn-create">Create New Article</a>
    </div>
    
    <section class="article-list">
        {% if articles %}
        <ul class="articles">
            {% for article in articles %}
            <li class="article-card">
                <article>
                    <h2 class="article-title">{{ article.title }}</h2>
                    <p class="article-meta"><strong>Author:</strong> {{ article.author }}</p>
                    <p class="article-meta"><strong>Date:</strong> {{ article.publication_date }}</p>
                    <p class="article-content-hp">
                        {{ article.content|truncatewords:40 }}...
                    </p>
                    <a href="{% url 'article_detail' article.id %}" class="btn-read" aria-label="Read more about {{ article.title }}">
                        Read more
                    </a>
                </article>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p class="no-articles">
            {% if query %}
                No articles found matching "<strong>{{ query }}</strong>".
            {% else %}
                No articles available.
            {% endif %}
        </p>
        {% endif %}
    </section>
</div>
{% endblock content %}

articles/templates/articles/create_article.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %}TruethLine | Create Article{% endblock title %}

{% block content %}
<div class="create-article-container">
    <h2 class="create-article-title-form">Create New Article</h2>
    <form action="{% url 'create_article' %}" method="post" class="create-article-form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="title">Title:</label>
            <input name="title" type="text" placeholder="Enter the title" required class="form-input">
        </div>

        <div class="form-group">
            <label for="author">Author:</label>
            <input name="author" type="text" placeholder="Author's name" required class="form-input">
        </div>

        <div class="form-group">
            <label for="content">Content:</label>
            <textarea name="content" placeholder="Write the article content" required class="form-textarea"></textarea>
        </div>

        <div class="form-group">
            <label for="publication_date">Publication Date:</label>
            <input name="publication_date" type="date" required class="form-input">
        </div>

        <button type="submit" class="submit-btn">Create Article</button>
    </form>
</div>
{% endblock content %}

articles/templates/articles/update_article.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %}TruethLine | Update Article{% endblock title %}

{% block content %}
<div class="create-article-container">
    <h2 class="create-article-title-form">Update your Article</h2>
    <form action="{% url 'update_article' article.id %}" method="post" class="create-article-form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>

        <div class="form-group">
            <label for="id_author">Author:</label>
            {{ form.author }}
        </div>

        <div class="form-group">
            <label for="id_content">Content:</label>
            {{ form.content }}
        </div>

        <button type="submit" class="submit-btn">UPDATE</button>
    </form>
</div>
{% endblock content %}